### ISSUE TITLE
银联支付 没有apply

### ISSUE THREAD

**Issue by Geekoo-Joker** [isandboy/SYPayKit#2]

**Comment by Geekoo-Joker** [comment]
银联支付里边 添加上 apply？

**Comment by isandboy** [comment]
你意思是银联apple pay吗

**Comment by isandboy** [comment]
@Geekoo-Joker 你意思是添加银联apple pay吗

**Comment by Geekoo-Joker** [comment]
可以吗？虽然我 找到了 另一个 单独支持 applePay的，不过我觉得 如果 这个里边也有的话 那就更好了。
这样 就不需要 使用多个源了

**Comment by isandboy** [comment]
@Geekoo-Joker 可以，我加下
